In [ ]:
# Step 1: Install necessary libraries
!pip install pandas openpyxl

# Step 2: Import libraries
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
# Step 3: Load both Excel files directly from the environment (replace with the correct file paths if needed)
# Specify the columns to load
selected_station = ['WIB','AWS IDMA2', 'WRF IDMA2']  # Replace with the actual column names or indices
# Load only the specified columns from the Excel file
df_pred = pd.read_excel('/content/6 Months WRF Results.xlsx', sheet_name="ALL-3DA", usecols=selected_station)

# Actual Meassured Data
df_actual = pd.read_excel('/content/IDMA2.xlsx', sheet_name="Data_Indramayu2")  # Actual data

In [ ]:
df_pred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2044 entries, 0 to 2043
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   WIB        2044 non-null   datetime64[ns]
 1   AWS IDMA2  2044 non-null   float64
 2   WRF IDMA2  2044 non-null   float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 48.0 KB

In [ ]:
df_actual.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 72 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   DateTime                                    8760 non-null   datetime64[ns]
 1   WIB                                         8760 non-null   datetime64[ns]
 2   Sun_Altitude                                8760 non-null   float64
 3   Sun_Azimuth                                 8760 non-null   float64
 4   Sun_Zenith_Angle                            8760 non-null   float64
 5   Day_of_Year_Calculation                     0 non-null      float64
 6   GHI Measurement                             0 non-null      float64
 7   DNI measurement                             0 non-null      float64
 8   DHI Measurement                             0 non-null      float64
 9   Pixel_46                                    0 non-null      float64
 10  Pixel_47                                    0 non-null      float64
 11  Pixel_48                                    0 non-null      float64
 12  Pixel_49                                    0 non-null      float64
 13  Pixel_50                                    0 non-null      float64
 14  Pixel_51                                    0 non-null      float64
 15  Pixel_52                                    0 non-null      float64
 16  Pixel_53                                    0 non-null      float64
 17  Pixel_54                                    0 non-null      float64
 18  ws_avg                                      8760 non-null   float64
 19  ws_max                                      8760 non-null   float64
 20  wd_avg                                      8760 non-null   float64
 21  tt_air_max                                  8760 non-null   float64
 22  tt_air_avg                                  8760 non-null   float64
 23  tt_air_min                                  8760 non-null   float64
 24  rh_avg                                      8760 non-null   float64
 25  pp_air                                      8760 non-null   float64
 26  sr_avg                                      8760 non-null   float64
 27  sr_max                                      8760 non-null   float64
 28  ws_2m                                       7337 non-null   float64
 29  AOD_1640nm                                  7709 non-null   float64
 30  AOD_1020nm                                  7709 non-null   float64
 31  AOD_870nm                                   7709 non-null   float64
 32  AOD_675nm                                   7709 non-null   float64
 33  AOD_500nm                                   7709 non-null   float64
 34  AOD_440nm                                   7709 non-null   float64
 35  AOD_380nm                                   7709 non-null   float64
 36  AOD_340nm                                   7709 non-null   float64
 37  Precipitable_Water(cm)                      7709 non-null   float64
 38  Triplet_Variability_1640                    7709 non-null   float64
 39  Triplet_Variability_1020                    7709 non-null   float64
 40  Triplet_Variability_870                     7709 non-null   float64
 41  Triplet_Variability_675                     7709 non-null   float64
 42  Triplet_Variability_500                     7709 non-null   float64
 43  Triplet_Variability_440                     7709 non-null   float64
 44  Triplet_Variability_380                     7709 non-null   float64
 45  Triplet_Variability_340                     7709 non-null   float64
 46  Triplet_Variability_Precipitable_Water(cm)  7709 non-null   float64
 47  440-870_Angstrom_Exponent                   7709 non-null   float64
 48  380-500_Angstrom_Exponent                   7709 non-null   float64
 49  440-675_Angstrom_Exponent                   7709 non-null   float64
 50  500-870_Angstrom_Exponent                   7709 non-null   float64
 51  340-440_Angstrom_Exponent                   7709 non-null   float64
 52  AERONET_Instrument_Number                   7709 non-null   float64
 53  Site_Latitude(Degrees)                      7709 non-null   float64
 54  Site_Longitude(Degrees)                     7709 non-null   float64
 55  Site_Elevation(m)                           7709 non-null   float64
 56  Solar_Zenith_Angle(Degrees)                 7709 non-null   float64
 57  Optical_Air_Mass                            7709 non-null   float64
 58  Sensor_Temperature(Degrees_C)               7709 non-null   float64
 59  Ozone(Dobson)                               7709 non-null   float64
 60  NO2(Dobson)                                 7709 non-null   float64
 61  Number_of_Wavelengths                       7709 non-null   float64
 62  Exact_Wavelengths_of_AOD(um)_1640nm         7709 non-null   float64
 63  Exact_Wavelengths_of_AOD(um)_1020nm         7709 non-null   float64
 64  Exact_Wavelengths_of_AOD(um)_870nm          7709 non-null   float64
 65  Exact_Wavelengths_of_AOD(um)_675nm          7709 non-null   float64
 66  Exact_Wavelengths_of_AOD(um)_500nm          7709 non-null   float64
 67  Exact_Wavelengths_of_AOD(um)_440nm          7709 non-null   float64
 68  Exact_Wavelengths_of_AOD(um)_380nm          7709 non-null   float64
 69  Exact_Wavelengths_of_AOD(um)_340nm          7709 non-null   float64
 70  Exact_Wavelengths_of_PW(um)_935nm           7709 non-null   float64
 71  Beta                                        0 non-null      float64
dtypes: datetime64[ns](2), float64(70)
memory usage: 4.8 MB

In [ ]:
# Step 4: Convert 'Tanggal' columns to datetime format for proper merging
df_pred['WIB'] = pd.to_datetime(df_pred['WIB'])
df_actual['WIB'] = pd.to_datetime(df_actual['WIB'])

# Step 5: Merge the two DataFrames on 'Tanggal' with an inner join (only common timestamps)
merged_df = pd.merge(df_pred, df_actual, on='WIB', how='inner', suffixes=('_pred', '_actual'))

# Step 7: Remove rows where any value in the specified columns is 0
# Assuming 'WRF IDMA1' and 'IDMA1' are part of the merged DataFrame
merged_df_clean = merged_df[(merged_df[['WRF IDMA2']] != 0).all(axis=1)]

# Step 8: Remove specific columns
columns_to_drop = ['Day_of_Year_Calculation', 'GHI Measurement', 'DNI measurement','DHI Measurement',  ]  # Replace with the columns you want to delete
merged_df_clean = merged_df_clean.drop(columns=columns_to_drop)

# Step 9: Export the cleaned DataFrame to a new Excel file
output_file_name = 'IDMA2+WRF_3DA.xlsx'
merged_df_clean.to_excel(output_file_name, index=False)

# Step 10: (Optional) Download the merged file if using Google Colab
from google.colab import files
files.download(output_file_name)

In [ ]:
merged_df_clean.head(10)

,WIB,AWS IDMA2,WRF IDMA2,DateTime,Sun_Altitude,Sun_Azimuth,Sun_Zenith_Angle,Pixel_46,Pixel_47,Pixel_48,...,Exact_Wavelengths_of_AOD(um)_1640nm,Exact_Wavelengths_of_AOD(um)_1020nm,Exact_Wavelengths_of_AOD(um)_870nm,Exact_Wavelengths_of_AOD(um)_675nm,Exact_Wavelengths_of_AOD(um)_500nm,Exact_Wavelengths_of_AOD(um)_440nm,Exact_Wavelengths_of_AOD(um)_380nm,Exact_Wavelengths_of_AOD(um)_340nm,Exact_Wavelengths_of_PW(um)_935nm,Beta
0,2023-01-03 07:00:00,172.32,222.397201,2023-01-03 00:00:00,18.113973,111.979116,71.886027,NaN,NaN,NaN,...,1.6391,1.0199,0.8701,0.6746,0.5006,0.4402,0.3793,0.34,0.937,NaN
1,2023-01-03 08:00:00,438.05,494.876129,2023-01-03 01:00:00,31.874870,112.933824,58.125130,NaN,NaN,NaN,...,1.6391,1.0199,0.8701,0.6746,0.5006,0.4402,0.3793,0.34,0.937,NaN
2,2023-01-03 09:00:00,459.98,702.702759,2023-01-03 02:00:00,45.441127,116.205652,44.558873,NaN,NaN,NaN,...,1.6391,1.0199,0.8701,0.6746,0.5006,0.4402,0.3793,0.34,0.937,NaN
3,2023-01-03 10:00:00,753.35,887.228638,2023-01-03 03:00:00,58.382499,124.105133,31.617501,NaN,NaN,NaN,...,1.6391,1.0199,0.8701,0.6746,0.5006,0.4402,0.3793,0.34,0.937,NaN
4,2023-01-03 11:00:00,587.22,994.663330,2023-01-03 04:00:00,69.334861,143.672748,20.665139,NaN,NaN,NaN,...,1.6391,1.0199,0.8701,0.6746,0.5006,0.4402,0.3793,0.34,0.937,NaN
5,2023-01-03 12:00:00,506.69,989.731445,2023-01-03 05:00:00,73.548336,186.124394,16.451664,NaN,NaN,NaN,...,1.6391,1.0199,0.8701,0.6746,0.5006,0.4402,0.3793,0.34,0.937,NaN
6,2023-01-03 13:00:00,577.08,938.877747,2023-01-03 06:00:00,66.950310,223.084637,23.049690,NaN,NaN,NaN,...,1.6391,1.0199,0.8701,0.6746,0.5006,0.4402,0.3793,0.34,0.937,NaN
7,2023-01-03 14:00:00,839.88,847.326965,2023-01-03 07:00:00,55.248280,238.586488,34.751720,NaN,NaN,NaN,...,1.6391,1.0199,0.8701,0.6746,0.5006,0.4402,0.3793,0.34,0.937,NaN
8,2023-01-03 15:00:00,322.47,658.849365,2023-01-03 08:00:00,42.080909,244.948126,47.919091,NaN,NaN,NaN,...,1.6391,1.0199,0.8701,0.6746,0.5006,0.4402,0.3793,0.34,0.937,NaN
9,2023-01-03 16:00:00,325.12,423.558227,2023-01-03 09:00:00,28.436586,247.514772,61.563414,NaN,NaN,NaN,...,1.6391,1.0199,0.8701,0.6746,0.5006,0.4402,0.3793,0.34,0.937,NaN